// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DrugAutocompleteController from "./drug_autocomplete_controller"
application.register("drug-autocomplete", DrugAutocompleteController)
