AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - 'spec/examples.txt'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'spec/factories/**/*'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 40
  Exclude:
    - 'app/controllers/**/*'

Metrics/AbcSize:
  Max: 36

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Naming/PredicatePrefix:
  Enabled: false

Style/EmptyElse:
  Enabled: false

