AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  Exclude:
    - 'spec/examples.txt'
    - 'bin/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'spec/factories/**/*'

Metrics/MethodLength:
  Max: 15

Layout/LineLength:
  Max: 120

Naming/PredicatePrefix:
  Enabled: false

Naming/PredicateMethod:
  Exclude:
    - 'app/models/prescription.rb'

Style/EmptyElse:
  Enabled: false

