# frozen_string_literal: true

# Represents a single prescription and tracks its state
# Belongs to a Patient (belongs_to :patient)
class Prescription < ApplicationRecord
  belongs_to :patient

  validates :drug_name, presence: true
  validates :drug_name, uniqueness: { scope: :patient_id }

  # Returns the name of the patient associated with this prescription
  #
  # This method provides a convenient way to access the patient's name without
  # directly accessing the patient object. It maintains encapsulation while
  # allowing the prescription to expose patient information when needed.
  #
  # @return [String] The name of the patient
  def patient_name
    patient.name
  end

  # Marks this prescription as created
  #
  # This method is called when a 'created' event is processed for this prescription.
  # It sets the flag that allows subsequent fill and return operations to proceed.
  # This enforces the business rule that prescriptions must be created before they can
  # be filled or returned.
  def mark_created
    update!(created: true)
  end

  # Processes a fill event for this prescription
  #
  # This method increments the fill count when a prescription is filled. It enforces
  # the business rule that a prescription must be created before it can be filled by
  # returning nil if the prescription hasn't been created yet. Returns self on success
  # to allow method chaining, or nil on failure.
  #
  # @return [Prescription, nil] self on success, nil if prescription hasn't been created
  def fill
    return nil unless created?

    increment!(:fill_count)
    self
  end

  # Processes a return event for this prescription
  #
  # This method increments the return count when a filled prescription is returned.
  # It enforces multiple business rules:
  # 1. The prescription must be created before it can be returned
  # 2. There must be at least one fill that hasn't been returned yet
  # This prevents returning more prescriptions than have been filled. Returns self on
  # success to allow method chaining, or nil on failure.
  #
  # @return [Prescription, nil] self on success, nil if prescription hasn't been created
  #                            or if there are no fills available to return
  def return_fill
    return nil unless created?
    return nil if fill_count <= return_count

    increment!(:return_count)
    self
  end

  # Calculates the net number of fills (fills minus returns)
  #
  # This method computes the effective number of fills by subtracting returns from
  # total fills. This is used in income calculations and reporting to show the
  # actual number of prescriptions that were successfully filled and not returned.
  #
  # @return [Integer] The net number of fills (fill_count - return_count)
  def net_fills
    fill_count - return_count
  end

  # Calculates the income generated by this prescription
  #
  # This method computes the total income based on fills and returns. The business
  # logic is:
  # - Each fill generates $5 in income
  # - Each return cancels the income from a fill AND incurs a $1 cost
  # The formula: (net_fills * 5) - (return_count * 1) ensures that returns both
  # cancel the fill income and add a penalty cost.
  #
  # @return [Integer] The total income (can be negative if returns exceed fills)
  def income
    # Each fill gives $5, but returns cancel the income from the fill AND cost $1
    # So: (net_fills * 5) - (return_count * 1)
    # This means: (fill_count - return_count) * 5 - return_count * 1
    (net_fills * 5) - return_count
  end
end
